Tc7210
jclehner/bcm2-utils pull request #42
Opened 2022-02-06 21:40 UTC by Nik014

`bcm2cfg` fails to parse some groups (firewall, tmmwifi & msc) but otherwise it seem to be working :) `bcm2dump` recognizes the model, I've successfully dumped `linux`, `image1`, `linuxkfs` & `linuxapps` images and extracted them with `ProgramStore`:
```
linux.bin LNXEF.01.36-kernel-20171205.bin
image1.bin TC7210-EF.01.36-171129-F-5FF.bin
linuxkfs.bin LNXEF.01.36-kernel-20171205.bin
linuxapps.bin LNXEF.01.36-apps-20171205.bin
```
Also dumped `dynnv.bin` and `bcm2cfg` parses it. Here are the logs: [tc7210_bcm2utils_logs.txt](https://github.com/jclehner/bcm2-utils/files/8011277/tc7210_bcm2utils_logs.txt)

2022-02-07 14:08 UTC, Nik014 commented
I've reverted to `TMM_7200` + zero padding for the `.cfg_md5key`. Running `bcm2cfg` now gives me:
```
$ bcm2cfg -P tc7210 info GatewaySettings.bin 
failed to parse group firewall
failed to parse group msc
GatewaySettings.bin
type    : gwsettings
profile : tc7210 (forced)
checksum: f97f19a3da9cee474640efc000157988 (ok)        # With TMM_7210 it was "(bad)"
size    : 25444 (ok)
key     : 0001020304050607080910111213141516171819202122232425262728293031
```

2022-02-14 16:41 UTC, jclehner requested changes
Please add the ProgramStore signature (`.pssig`), as suggested. Also, please dump the bootloader, and send me a sample, so we can add `.blsig` too.

2022-02-14 16:41 UTC, jclehner commented on profiledef.c
> +		.pretty = "Technicolor TC7210",
```suggestion
		.pretty = "Technicolor TC7210",
		.pssig = 0xa82c,
```

2022-02-14 20:05 UTC, Nik014 commented on profiledef.c
> +		.pretty = "Technicolor TC7210",
I've sent you an email with the dumps.

2022-02-15 11:02 UTC, merged